### PR TITLE
Lua 5.2 bindings

### PR DESCRIPTION
**Pull request by rikkimax**
Tested on windows using dmd and lua 5.2 binaries for 32 bit.

### CODE REVIEW

**Comment by mdparker** [comment]
I don't see that the lua license header is required for this. I've gone through this with others, Sam Lantinga from SDL in particular regarding the LGPL, and the consensus is that when you are creating a binding to a library, you are not bound by the library's license. It's the implementation that's licensed, not the interface. Whoever uses the binding must also use the library itself and they are bound by the license.

You'll notice that there is one and only one license in Derelict. To do otherwise would complicate things. If the Lua maintainers actually told you that they expect you to include the lua license header with a binding, that's a different story. And in that case, I don't want to add it to Derelict. Otherwise, I'll merge it in if you remove the lua license. I was hoping to do this eventually anyway, though I was going to bind to 5.1 in order to enable use of LuaJIT.

**Comment by rikkimax** [comment]
Okay I wasn't 100% sure it was needed. I'll do it when i get home.
If its still wanted for 5.1 I'll probably do it over next few weeks.

**Comment by rikkimax** [comment]
Okay removed commit from vcs.
On the note of the closing that was just me on tablet, and pressing wrong button.

**Comment by mdparker** [comment]
When you say you removed the commit, I assume you mean the one with the license header? It didn't get removed from the pull request (is that even possible?). Anyway, I'll see about merging it as is, then I'll remove the license header myself.

**Comment by rikkimax** [comment]
Sorry I do remember removing it and it pushing to github which I confirmed. and yes possible if you update on branch while you have pull request it'll update pull request or i5 did atleast with this one.

**Comment by rikkimax** [comment]
Right redone the removal. If it still hasn't removed and fully moved to pull request (which it appears to be) I can recreate pull request but it appears to be fine.

**Comment by mdparker** [comment]
Roger that. Thanks!

**Pull request merged**
