### PR TITLE
FreeType cannot always bind FT_Get_PS_Font_Value.

### PR DESCRIPTION
**Pull request by vova616**
This function only available in 2.4.8+.

### CODE REVIEW

**Comment by mdparker** [comment]
If you don't need to use it, you can use the selective loading mechanism to ignore it. See [derelict.util.exception](https://github.com/aldacron/Derelict3/blob/master/import/derelict/util/exception.d#L123) for details about the MissingSymbolCallback. It exists precisely for this purpose.

**Comment by vova616** [comment]
Ah thanks cool, maybe its worth mentioning it in the README?

**Comment by mdparker** [comment]
Not anymore. I was going to document it on the wiki here, but I've changed it a bit and documented it in the new DerelictUtil repo at [DerelictOrg](https://github.com/DerelictOrg). I've also copied the FreeType binding over there. If all of the Derelict packages you are using have been copied over already, I recommend you switch to those. DerelictUtil is mostly documented there.

**Comment by vova616** [comment]
Awesome, thanks.

**Pull request closed without merging**
