### PR TITLE
Mac support for Devil

### PR DESCRIPTION
**Pull request by hadronized**
I made 2 commits that allows us to use DerelictIL on Mac. I tested it on my own Macbook Pro, OSX 10.7.4.

### CODE REVIEW

**Comment by mdparker** [comment]
What about ILU and ILUT? Are the library names libILU.dylib and libILUT.dylib? I assume this is the case but I want to make sure. If merge your pull request I should also add those in.

**Comment by hadronized** [comment]
I'm gonna figure it out and will let you know.

**Comment by hadronized** [comment]
Ok I fixed it for ILU and ILUT, what should I do now? Create a new pull request?

**Comment by mdparker** [comment]
No, that's fine. I'll update on my end and push it. I just wanted to verify the lib names were correct.

**Comment by mdparker** [comment]
Well, I don't have to. It's already there. Thanks!

**Comment by hadronized** [comment]
You're welcome!

**Pull request merged**
