### PR TITLE
Lua and SDL

### PR DESCRIPTION
**Pull request by Flamaros**
Some few fixes.

The most important commit is the one which add some extern(c) on lua call back to solve parameter corruptions.

Other commits just add libraries file path to fix loading issues on some platforms.

### CODE REVIEW

**Comment by mdparker** [comment]
A few comments.
- I don't want to add any writeln statements to the function binder. There's no reason for it. All of the relevant information is contained in the SymbolLoadException when that's thrown by the loader. If not caught, that will already be printed out to the console when it's open. Otherwise it can be caught and printed elsewhere if necessary.
- I should have been more vigilant when I merged the pull request that added Lua. I see now there are a number of problems with it besides the incorrect library names (the one for Linux is wrong as well). All of those const types need to be replaced with enums, for one. At any rate, you actually appear to be removing the extern(C) from the function pointer aliases. I merged a pull request that added those some time ago.
- The paths for SDL2_image are good, but I don't think adding SDL.dll to the SDL2 loader is such a good idea. SDL.dll is for SDL 1.2, which isn't even compatible with this binding. If, for some reason, anyone decided to rename SDL2.dll, they can use DerelictSDL2.load("SDL.dll"), but it shouldn't be part of the default.

Thanks for submitting this, but I'm going to close it without merging it. Later today, I'll make the change to the SDL_image loader and do some major modifications on the Lua binding.

**Comment by Flamaros** [comment]
Ok, thank.

For SDL.dll issue I'll take a look with SDL developer if the generated library filename can be change to include the major version number.

For Lua I didn't touch const values as right values as used, but it's right that enum is certainly better. Currently I added extern(C) to the function pointer aliases. I certainly did something wrong because it's my first pull request and I got some difficulties to switch submodule on a fresh fork (before I had only copy some parts of derelict on my project repository).
I fixed only what I had test for Lua, but I saw that the MacOS X library certainly have the wrong name too.

**Comment by mdparker** [comment]
I'm not sure what you're seeing with SDL, but when I checkout the latest SDL2 snapshot and build with configure and make, it generates an SDL2.dll.

**Comment by Flamaros** [comment]
It's because I used Visual Studio 2012 project instead of configure and make method.

**Pull request closed without merging**
