### PR TITLE
Added some missing functions for the tcod binding.

### PR DESCRIPTION
**Pull request by oaalto**

### CODE REVIEW

**Comment by mdparker** [comment]
I'm really not maintaining this anymore. I'll go ahead and merge this one, but no promises in the future.

**Comment by oaalto** [comment]
Ok, thanks. How much effort you'd say it would take to move the tcod
bindings to DerelictOrg?

On Thu, Jul 17, 2014 at 1:15 AM, Mike Parker notifications@github.com
wrote:

> Merged #179 https://github.com/aldacron/Derelict3/pull/179.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aldacron/Derelict3/pull/179#event-142407245.

## 

O.

**Comment by mdparker** [comment]
Not much. It's just a matter of setting up the repository, a new dub project and reformatting the source (for which I have a couple of scripts). I haven't yet because I don't use it and no one has asked me to, but I can put it on my TODO list. Maybe I can get around to it this weekend. I've got some other Derelict-related stuff to knock out first.

**Comment by oaalto** [comment]
That would be great. Especially if it makes it easier for you the receive
pull requests for it. (if it has any problems left, that is)

O.

On Thu, Jul 17, 2014 at 2:00 PM, Mike Parker notifications@github.com
wrote:

> Not much. It's just a matter of setting up the repository, a new dub
> project and reformatting the source (for which I have a couple of scripts).
> I haven't yet because I don't use it and no one has asked me to, but I can
> put it on my TODO list. Maybe I can get around to it this weekend. I've got
> some other Derelict-related stuff to knock out first.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aldacron/Derelict3/pull/179#issuecomment-49292420.

## 

O.

**Pull request merged**
