### PR TITLE
Remove glfwGetScrollOffset.

### PR DESCRIPTION
**Pull request by ghost**
More syncing.

### CODE REVIEW

**Comment by mdparker** [comment]
Thanks again!

**Comment by malkia** [comment]
Why was this removed?

It's useful to have the non-callback version available, for places like dynamic languages where callbacks from "C" side are harder, or more expensive to have.

**Comment by mdparker** [comment]
You'll have to take that up with the GLFW maintainer. It was removed from the GLFW API, so there's nothing we can do about it. Can't bind to what isn't there!

**Comment by malkia** [comment]
I'm actually very sorry for posting this on the wrong forum, also read later Elmindreda (glfw's author) comments why it was removed - and it makes sense now.

**Comment by mdparker** [comment]
No worries!

**Pull request merged**
