### PR TITLE
OpenCL bindings.

### PR DESCRIPTION
**Pull request by vuaru**
I created OpenCL bindings derelict-style, with much help from cl4d and your blog posts.
Tested on Windows only.

### CODE REVIEW

**Comment by NCrashed** [comment]
OpenCL module isn't integrated with build script. Under linux there are compilation issues in constants.d, dmd reads Windows version of CL_FLT_MIN, CL_DBL_MIN anyway (possible compiler bug). I will try to fix it, I am extremely interested in DerelictOpenCL module, due cl4d doesn't work under Linux.

**Comment by vuaru** [comment]
Thanks for testing :)

Honestly I wasn't sure if I should add all those number constants at all, they seemed pretty useless to me..

**Comment by NCrashed** [comment]
Its my pleasure.

These constants are ridiculous in D context, but they should exist to achieve max backward compatibility with original OpenCL code and documentation.

**Comment by mdparker** [comment]
Just wanted to let you know that I'll look into this as soon as I get back to Korea next week after DConf.

**Comment by vuaru** [comment]
Great!

I see github keeps adding any commits in the repo to this discussion.. odd.

**Comment by mdparker** [comment]
OK, a cursory scan looks pretty good. I just want to highlight a few things.
- Derelict_OS_Posix is defined on Mac in addition to Linux and *BSD (since DMD defines Posix on Mac), so are you sure that OpenCL is distributed as an .so there? I know OpenGL is a Framework. If it's not an .so, then you need to add a test for Derelict_OS_Mac before the Posix check implement the proper lib name or do a static if(Derelict_OS_Posix && !Derelict_OS_Mac)
- All of the D3D stuff needs to be in a Derelict_OS_Windows (or version(Windows) block.
- Please make sure to convert all tabs to spaces and remove trailing spaces. If you haven't already, it's not critical as I can do it myself, but it's nice if I don't have to.

**Comment by vuaru** [comment]
This should be it :)

**Comment by mdparker** [comment]
Awesome, thanks! Now I've got to figure out how to merge this. It tells me it can't automatically merge it and I need to use the command line to resolve conflicts. Never done that before. Let's see how it goes.

**Comment by mdparker** [comment]
OK, this is apparently going to take more time than I've got right now. I need to learn how to resolve merge conflicts. The conflict is coming from your fork being out of sync with the Derelict 3 repo. Several commits have been made recently. I'll figure this out when I get a chance.

**Comment by vuaru** [comment]
Should be up to date now.
(screwed up the merge at first, oops..)

**Comment by mdparker** [comment]
Awesome! Thanks.

**Comment by mdparker** [comment]
Ugh. Looks like I got more than I expected it when I merged this. I didn't realize you had changed the directory tree.

**Comment by mdparker** [comment]
Sorry, but I had to revert the merge. I have no plans to change the directory layout. What I will do though is clone your repo and manually add the OpenCL binding to mine. I'll open a new issue as a reminder for myself.

**Comment by vuaru** [comment]
My bad, I did that after I'd opened this pull request..

**Pull request merged**
