### PR TITLE
PostgreSQL bindings

### PR DESCRIPTION
**Pull request by NCrashed**
I have run into problem with PostgreSQL bindings in dpq2. There wasn't any libpq.lib in omf format, that's why i wrote this module. Functions and types were extracted from postgres 9.2 headers and were checked with dpq2 bindings. 
Tested on win7 x86_64 and fedora 17 x86_64.

### CODE REVIEW

**Comment by mdparker** [comment]
Looks great! But I'm going to have to respectfully decline the pull request. From the beginning, I've had a very narrow scope with Derelict, specifically targeting libraries that are primarily useful in multimedia apps and games. The only exception I've made in the 8 years or so I've been maintaining it is Lua, and I did so because it's so commonly used for game scripting. Database bindings are something else entirely and I'm afraid if I start letting those in I'll be on the road to Derelict becoming a general binding project. Ultimately, I'm the one who has to maintain it, so the fewer packages the better from my perspective. I'll be happy to put up a link to it in the readme (perhaps I should get a wiki going again) and on my D blog.

**Comment by simendsjo** [comment]
@aldacron: Why not let Derelict be a general binding project, and let each library be an additional download (through DUB for instance).

**Comment by mdparker** [comment]
I'm really hesitant to do that. In my experience, people who submit new bindings never maintain them. Then I'm the one who has to keep up with all the libraries to keep them up to date. It's gotten better here on github with the pull requests I get for the more commonly used packages (glfw3, sdl2), but ultimately it all comes down to me. And that's my biggest concern. OTHOH, if there's enough demand for that sort of thing, then I suppose I'll relent.

**Comment by NCrashed** [comment]
It is weird situation with lack of general dynamic bindings. Derelict has great shared lib loading mechanism solving annoying "coff <-> omf" problem. But if it is only multimedia bindings library, I am going to create separate project to maintain my bindings.
@simendsjo: It would be great to have repository alike Haskell Hackage for D, but I think there are huge amount of pitfalls to implement uniform package interface and maintain them to be up to date.

**Comment by simendsjo** [comment]
@aldacron: I was thinking that Derelict could just be the core, and all libraries available through add-ons in a package manager.
@NCrashed: There is DUB and Orbit. DUB is working today, and already have several packages.

**Comment by mdparker** [comment]
@NCrashed You make a good point about the lack of general dynamic bindings. I suppose it may be time to open up a bit. github certainly makes it easier to do so than when DSource was the primary Derelict repo.

@simendsjo I'm definitely interested in taking advantage of whichever package manager becomes the de facto standard, be it DUB or Orbit. I'm going to wait a little bit though, to see which one catches on.

**Comment by denizzzka** [comment]
Does anyone know any other language why ​​have similar collections of bindings as proposed by simendsjo?

**Pull request merged**
