### PR TITLE
SDL2 update and fixes

### PR DESCRIPTION
**Pull request by CyberShadow**
An API update, a fix in a macro, and some whitespace trimmings.

Did the API update with [these](https://gist.github.com/CyberShadow/5116907). Not sure how it's supposed to be done or if there's an easier way.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Oh, almost forgot. Here's the SDL2.dll I built and used for testing:
http://dump.thecybershadow.net/8736c03296acf915e31f0f372c971437/SDL2.dll
(SDL2 hg 177d1dc3dba6, release configuration)

**Comment by CyberShadow** [comment]
Good news: [The SDL 2 ABI has been frozen](http://forums.libsdl.org/viewtopic.php?t=8892)!

Also, I noticed there were some `SDL_REVISION` constants. Updated those + one more recent API change.

**Comment by mdparker** [comment]
Sorry for the delay. I've been afk for a couple of days. Ideally, the baseline for the binding should be the source snapshot they release at http://www.libsdl.org/hg.php. I got off track a while back with a pull request that updated to the latest mercurial head. That caused a bit of confusion until a new snapshot was released and I could stabilize on that. So I think what I'll do is keep this open, then when the next snapshot is released I'll merge it in before catching up.

**Comment by CyberShadow** [comment]
Ah, OK! In theory this pull should be good to go whenever that happens, considering the ABI freeze.

In that case, it might make sense to update the SDL2.dll download so it's in sync with Derelict 3 master.

**Comment by mdparker** [comment]
Unfortunately, I can't do anything about the DLL. Github disabled downloads not that long ago. I can't even delete it.

**Comment by CyberShadow** [comment]
Why not change the link, then?

**Comment by mdparker** [comment]
Ah, in the readme. Because I forgot all about it. Thanks!

**Comment by mdparker** [comment]
The snapshot was recently updated. So I'll go ahead and merge this. Then I'll look into what else needs to be done to get current.

**Pull request merged**
