### PR TITLE
API changes were made two days ago

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mdparker** [comment]
I'm clear on the GLFW changes (noticed that on the mailing list the other day), but not on the changes to DerelictFI. First, why are they in the same pull request? Second, what's the deal with the architecture flag?

**Comment by ghost** [comment]
Should we mix version statements and static statements? If not, should I add a win32 enum instead? FreeImage has a preprocessor directive that looks like this: "#ifndef _win32" (but not in the header, which confused me).

I've barely used version control systems before, nor have I used github particularly much, which is why I didn't think of creating branches until after I had already executed a pull, but I'll try to remember that until next time.

**Comment by mdparker** [comment]
My problem is not with the version statement vs. static if, but with the actual purpose of adding the flags to the FreeImage bidning. I'm looking at the header for FreeImage 3.15.4 and I don't see any defines wrapping FreeImage_RegisterExternalPlugin at all.

EDIT:
Ah, I see. I just now parsed your "but not in the header" comment.

**Comment by mdparker** [comment]
OK, I've got that bit sorted now. But still, I don't see anything referring to the X86 architecture in the FreeImage source. So before I merge the pull request I want to understand why you've added it.

**Comment by ghost** [comment]
It has "#ifndef _win32" wrapped around it. Derelict tries to bind it, but fails, because the symbol is not included in the library on platforms other than win32. Is an X86 + Windows check not good enough? Should I define Derelict_OS_Win32 or something? I could replace it with version (Win32), but that's not very consistent.

Am I missing anything?

**Comment by mdparker** [comment]
I have no problem with the Win32 check. I understand that part. I was just wondering why you added a flag for x86. There's no check for x86 in the FreeImage source that I see, so the Win32 check by itself should be sufficient. I'll go ahead and merge this when I get home tonight, but I'll remove the x86 flag. Thanks!

**Comment by ghost** [comment]
Right, but we need another enum for that then.

**Comment by mdparker** [comment]
No, there is absolutely no need for it right now. There is nothing in Derelict that is x86-dependent. A solitary static if(Derelict_OS_Windows) is fine. I don't quite understand why you are conflating the two.

EDIT: It just dawned on me that you might be trying to differentiate between 64-bit and 32-bit windows, in which case that's not necessary. _win32 is defined in C compilers even on 64-bit Windows. It means that the Win32 API is available, not that the platform is 32-bit. So it can be implemented in D code as version(Windows) to cover both 32 and 64-bit platforms, or via Derelict_OS_Windows in Derelict. Not to mention the fact that Windows 8 runs on ARM devices and it is conceivable that GDC or LDC could be ported there in the future.

**Comment by ghost** [comment]
That makes sense...

Alright, I'll try to fix this.

**Pull request closed without merging**
